# Generated by Django 4.2.28 on 2026-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('grants', 'Grants & Philanthropy'), ('vc', 'Venture Capital'), ('impact', 'Impact Investment'), ('loans', 'Loans & Financing'), ('government', 'Government Programs'), ('crowdfunding', 'Crowdfunding')], max_length=50)),
                ('funding_type', models.CharField(choices=[('grants', 'Grants'), ('equity', 'Equity Investment'), ('debt', 'Loans/Debt'), ('mixed', 'Mixed Funding'), ('government', 'Government Programs')], max_length=50)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('typical_investment_range', models.CharField(blank=True, max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Capital Source',
                'verbose_name_plural': 'Capital Sources',
            },
        ),
        migrations.CreateModel(
            name='DirectorySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('project', 'Land-Based Project'), ('service', 'Service Provider'), ('capital', 'Capital Source')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('data', models.JSONField()),
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitter_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandBasedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('farm', 'Regenerative Farm'), ('retreat', 'Retreat Center'), ('community', 'Intentional Community'), ('research', 'Research Center'), ('education', 'Educational Center'), ('rewilding', 'Rewilding Project'), ('ranch', 'Regenerative Ranch')], max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Land-Based Project',
                'verbose_name_plural': 'Land-Based Projects',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('design', 'Design & Consulting'), ('implementation', 'Implementation'), ('education', 'Education & Training'), ('research', 'Research'), ('restoration', 'Ecological Restoration'), ('architecture', 'Regenerative Architecture'), ('agriculture', 'Agriculture Consulting')], max_length=50)),
                ('services', models.JSONField(blank=True, default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('service_area', models.CharField(blank=True, help_text='Geographic service area', max_length=255)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
            },
        ),
    ]
