# Generated by Django 4.2.28 on 2026-02-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('founding', 'Founding Sponsor'), ('platinum', 'Platinum Sponsor'), ('gold', 'Gold Sponsor'), ('silver', 'Silver Sponsor'), ('community', 'Community Supporter')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('logo_url', models.URLField()),
                ('website_url', models.URLField()),
                ('description', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-featured', 'tier', 'joined_at'],
            },
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='claimed_by',
            field=models.EmailField(blank=True, help_text='Email of person who claimed this enterprise', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs'),
        ),
        migrations.AddField(
            model_name='landbasedproject',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='landbasedproject',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landbasedproject',
            name='claimed_by',
            field=models.EmailField(blank=True, help_text='Email of person who claimed this enterprise', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landbasedproject',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='claimed_by',
            field=models.EmailField(blank=True, help_text='Email of person who claimed this enterprise', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs'),
        ),
    ]
